songs = [
    {
        'title': 'VERY NICE',
        'artist': 'Seventeen',
        'album': 'Love&Letter',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'FaSHioN',
        'artist': 'Cortis',
        'album': 'COLOR OUTSIDE THE LINES',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Cool With You',
        'artist': 'NewJeans',
        'album': 'Get Up',
        'mood': 'chill',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Butterfly',
        'artist': 'BTS',
        'album': 'The Most Beautiful Moment in Life, Pt. 2',
        'mood': 'sad',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Shoot Out',
        'artist': 'Monsta X',
        'album': 'Take.1 Are You There?',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Magnetic',
        'artist': 'ILLIT',
        'album': 'SUPER REAL ME',
        'mood': 'romantic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Danger',
        'artist': 'BTS',
        'album': 'Dark & Wild',
        'mood': 'dark',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': "God's Menu",
        'artist': 'Stray Kids',
        'album': 'GO LIVE',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Blueprint',
        'artist': 'Stray Kids',
        'album': 'GO LIVE',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Deja Vu',
        'artist': 'ATEEZ',
        'album': 'ZERO : FEVER Part.3',
        'mood': 'dark',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Muddy Water',
        'artist': 'Stray Kids',
        'album': 'ODDINARY',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'FANCY',
        'artist': 'TWICE',
        'album': 'FANCY YOU',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Boy With Luv',
        'artist': 'BTS feat. Halsey',
        'album': 'MAP OF THE SOUL : PERSONA',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Jam Jam',
        'artist': 'IU',
        'album': 'Palette',
        'mood': 'chill',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Love wins all',
        'artist': 'IU',
        'album': 'Love wins all',
        'mood': 'sad',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Dumb Litty',
        'artist': 'KARD',
        'album': 'Dumb Litty',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Love Shot',
        'artist': 'EXO',
        'album': 'LOVE SHOT',
        'mood': 'romantic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Any Song',
        'artist': 'ZICO',
        'album': 'Any Song',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'I Am You, You Are Me',
        'artist': 'ZICO',
        'album': 'Break Up 2 Make Up',
        'mood': 'chill',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Spring Day',
        'artist': 'BTS',
        'album': 'You Never Walk Alone',
        'mood': 'sad',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Kidult',
        'artist': 'Seventeen',
        'album': 'Heng:garae',
        'mood': 'nostalgic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Gone Away',
        'artist': 'Stray Kids',
        'album': 'NOEASY',
        'mood': 'sad',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'LOVE SCENARIO',
        'artist': 'iKON',
        'album': 'Return',
        'mood': 'romantic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'LOVE DIVE',
        'artist': 'IVE',
        'album': 'LOVE DIVE',
        'mood': 'romantic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Love Me Right',
        'artist': 'EXO',
        'album': 'LOVE ME RIGHT',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Ring Ding Dong',
        'artist': 'SHINee',
        'album': '2009, Year Of Us',
        'mood': 'nostalgic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Replay',
        'artist': 'SHINee',
        'album': 'Replay',
        'mood': 'nostalgic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Lucifer',
        'artist': 'SHINee',
        'album': 'Lucifer',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'LILAC',
        'artist': 'IU',
        'album': 'LILAC',
        'mood': 'dreamy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'ILLELLA',
        'artist': 'MAMAMOO',
        'album': 'MIC ON',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'HIP',
        'artist': 'MAMAMOO',
        'album': 'reality in BLACK',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Maria',
        'artist': 'HWASA',
        'album': 'María',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Okey Dokey',
        'artist': 'MINO & ZICO',
        'album': 'Show Me The Money 4',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Chewing Gum',
        'artist': 'NCT DREAM',
        'album': 'Chewing Gum',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Regular - English Version',
        'artist': 'NCT 127',
        'album': 'Regular-Irregular',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Kick It',
        'artist': 'NCT 127',
        'album': 'Neo Zone',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Cherry Bomb',
        'artist': 'NCT 127',
        'album': 'Cherry Bomb',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'One and Only',
        'artist': 'BOYNEXTDOOR',
        'album': 'WHO!',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Given-Taken',
        'artist': 'ENHYPEN',
        'album': 'BORDER : DAY ONE',
        'mood': 'dreamy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Drunk-Dazed',
        'artist': 'ENHYPEN',
        'album': 'BORDER : CARNIVAL',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Sugar Rush Ride',
        'artist': 'TXT',
        'album': 'The Name Chapter: TEMPTATION',
        'mood': 'dreamy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Super',
        'artist': 'Seventeen',
        'album': 'FML',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'RHYTHM TA',
        'artist': 'iKON',
        'album': 'WELCOME BACK',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'HIT',
        'artist': 'Seventeen',
        'album': 'An Ode',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': '_WORLD',
        'artist': 'Seventeen',
        'album': 'SECTOR 17',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'FANTASTIC BABY',
        'artist': 'BIGBANG',
        'album': 'ALIVE',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'BANG BANG BANG',
        'artist': 'BIGBANG',
        'album': 'MADE',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'illa illa',
        'artist': 'B.I',
        'album': 'WATERFALL',
        'mood': 'nostalgic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'FEARLESS',
        'artist': 'LE SSERAFIM',
        'album': 'FEARLESS',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Impurities',
        'artist': 'LE SSERAFIM',
        'album': 'ANTIFRAGILE',
        'mood': 'chill',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'ANTIFRAGILE',
        'artist': 'LE SSERAFIM',
        'album': 'ANTIFRAGILE',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Hype Boy',
        'artist': 'NewJeans',
        'album': 'New Jeans',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'BTBT',
        'artist': 'B.I',
        'album': 'BTBT',
        'mood': 'chill',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Thunderous',
        'artist': 'Stray Kids',
        'album': 'NOEASY',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'TOMBOY',
        'artist': '(G)I-DLE',
        'album': 'I NEVER DIE',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'HOT',
        'artist': 'Seventeen',
        'album': 'Face the Sun',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'LALISA',
        'artist': 'LISA',
        'album': 'LALISA',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'ATTITUDE',
        'artist': 'IVE',
        'album': 'IVE EMPATHY',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Queencard',
        'artist': '(G)I-DLE',
        'album': 'I feel',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Attention',
        'artist': 'NewJeans',
        'album': 'New Jeans',
        'mood': 'chill',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Drama',
        'artist': 'aespa',
        'album': 'Drama',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Whiplash',
        'artist': 'aespa',
        'album': 'Whiplash',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Armageddon',
        'artist': 'aespa',
        'album': 'Armageddon',
        'mood': 'dark',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Supernova',
        'artist': 'aespa',
        'album': 'Armageddon',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Baggy Jeans',
        'artist': 'NCT U',
        'album': 'Golden Age',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Fighting',
        'artist': 'BSS feat. Lee Young Ji',
        'album': 'SECOND WIND',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'BOUNCY',
        'artist': 'ATEEZ',
        'album': 'THE WORLD EP.2 : OUTLAW',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'WORK',
        'artist': 'ATEEZ',
        'album': 'GOLDEN HOUR : Part.1',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'LOCO',
        'artist': 'ITZY',
        'album': 'CRAZY IN LOVE',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Hollywood Action',
        'artist': 'BOYNEXTDOOR',
        'album': 'No Genre',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'If I Say, I Love You',
        'artist': 'BOYNEXTDOOR',
        'album': 'No Genre',
        'mood': 'romantic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': '404(new era)',
        'artist': 'KiiiKiii',
        'album': 'UNCUT GEM',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Rude!',
        'artist': 'Hearts2Hearts',
        'album': 'FOCUS',
        'mood': 'confident',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': "Moonwalkin'",
        'artist': 'LNGSHOT',
        'album': "Moonwalkin'",
        'mood': 'chill',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'GO!',
        'artist': 'Cortis',
        'album': 'COLOR OUTSIDE THE LINES',
        'mood': 'energetic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'JoyRide',
        'artist': 'Cortis',
        'album': 'COLOR OUTSIDE THE LINES',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'REDRED',
        'artist': 'Cortis',
        'album': 'COLOR OUTSIDE THE LINES',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'My House',
        'artist': '2PM',
        'album': 'No.5',
        'mood': 'nostalgic',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'In Bloom',
        'artist': 'ZEROBASEONE',
        'album': 'YOUTH IN THE SHADE',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'TOPLINE',
        'artist': 'Stray Kids feat. Tiger JK',
        'album': '5-STAR',
        'mood': 'aggressive',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'Super Shy',
        'artist': 'NewJeans',
        'album': 'Get Up',
        'mood': 'happy',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'HALAZIA',
        'artist': 'ATEEZ',
        'album': 'SPIN OFF : FROM THE WITNESS',
        'mood': 'dark',
        'cover_art': '',
        'spotify_link': '',
    },
    {
        'title': 'All My Poetry',
        'artist': 'CLOSE YOUR EYES',
        'album': 'ETERNALT',
        'mood': 'sad',
        'cover_art': '',
        'spotify_link': '',
    },
]
